### ISSUE TITLE
播放音乐  声音卡顿？

### ISSUE THREAD

**Issue by mytaihong** [zhangliangming/HappyPlayer-AS#1]
如题

**Comment by zhangliangming** [comment]
你是说播放ape格式的音频吗，还是说所有的音频格式都会有卡盾的情况。。能说一下，具体的音频格式吗？

**Comment by zhangliangming** [comment]
ape格式用了网上的jmac-1.74.jar来解码， 该jar包在java端解码还是比较快的，在android机上解码会有一定的耗时,所以导致了在刚播放的时候会卡，定位播放的时候也会卡。这个我也向jmac的作者反馈了，不过他还没有修复，所以这部分，就无能为力了。
