### ISSUE TITLE
如果扫不出歌曲看这里。

### ISSUE THREAD

**Issue by 516457377** [zhangliangming/HappyPlayer-AS#2]
辛辛苦苦弄了一天，因为权限问题。。在ScaningActivity里面扫描歌曲需要动态添加权限不然在6.0以上的系统会扫不出歌曲来。
好不容易弄出来了歌曲然后播放ape发现会卡顿。。在芯片比较差的机器会这样。好点的就很流畅。。我就是因为这个原因来找这个项目的。。结果欸还是卡。不知道网易云的是怎么弄得。他那个播放ape就不卡。
不过还是辛苦博主了。项目还是很不错的。

**Comment by zhangliangming** [comment]
1.多谢516457377 ，因为我手机系统一直都是5.0系统的，所以不知道在6.0以上存在权限的问题，再次感谢，下个版本可能会对这个项目进行重构、修复和添加新功能。
2.ape格式用了网上的jmac-1.74.jar来解码， 该jar包在java端解码还是比较快的，在android机上解码会有一定的耗时,所以导致了在刚播放的时候会卡，定位播放的时候也会卡。这个我也向jmac的作者反馈了，不过他还没有修复，所以这部分，就无能为力了。
