### ISSUE TITLE
你好，想问下flac网络音乐的边缓存边播放是怎么做的？

### ISSUE THREAD

**Issue by andriodZ** [zhangliangming/HappyPlayer-AS#3]

**Comment by zhangliangming** [comment]
我之前实现的方式是，下载单个音频文件（aa.flac），开始的时间判断文件已下载的大小，如果文件已下载200kb，则播放本地的音频文件。因为音频文件只要下载了部分头文件后，就可以播放了，不一定要全部下载完成后，才可以播放的。最后就是MediaPlayer播放结束后，判断结束时间A是否与整个音频文件的总时间L相等，如果不相等，则重新加载本地音频文件，seekto到A的时间播放。当前这样会有一点点的卡顿。希望可以帮到你。

**Comment by andriodZ** [comment]
@zhangliangming 我目前就是这么做的，但是他卡顿的特别厉害，感觉就是断音了

**Comment by zhangliangming** [comment]
如果只有flac音频文件是这样，你可以通过输入解码的耗时等方式来跟踪，看看具体那一个步骤浪费了太多的时间。能问一下，你是用什么来解码的吗？

**Comment by andriodZ** [comment]
@zhangliangming 对这方面不是很了解，播放音频文件需要进行解码嘛？不是直接设置播放地址就可以了么

**Comment by zhangliangming** [comment]
如果使用系统自带的MediaPlayer，支持的音频格式比较少，就是mp3等格式，不支持flac格式的。

**Comment by andriodZ** [comment]
@zhangliangming 能否推荐一些资料？不胜感激。谢谢

**Comment by zhangliangming** [comment]
我自己都是网上查资料的，一般百度一下就有了
